# General setup

results_dir: "results"
data_gen_script: "scripts/experiment_1.py"
front_gen_script: "scripts/generate_front.py"
summary_stats_script: "scripts/summary_statistics.py"
thresholds_script: "scripts/compute_thresholds.py"
result_extension: "parquet"

# NSGA2 options

xover_probability: 0.9
xover_distribution: 20
tournament_size: 2
distribution_index: 20

# Data generation

modes: ["baseline", "relaxed", "ranking"]
population_sizes: [6, 12, 18]
n_generations: 150
n_runs: 500

# Front generation

n_generations_front: 10000
population_size_front: 1000

# List of all considered problems
threshold_improvement_percentages: [0.01, 0.05, 0.10] # low, med, high

problems:
  - name: "branin"
    constraint_symbols: ["c_1"]
    objective_symbol: "f_1"
    objective_optimum: -268.78792

  - name: "mystery"
    constraint_symbols: ["c_1"]
    objective_symbol: "f_1"
    objective_optimum: -1.174261

  # - name: "mishrasbird"
  # constraint_symbol: "c_1"
  # objective_symbol: "f_1"
  # constraint_thresholds: [1.0, 2.0, 3.0, 4.0, 5.0]

## problems for which summary statistics make sense

summary_problems: ["branin", "mystery"]
